version: "3.9"
services:
  mysqldata:
    build: 
        context: .
        dockerfile: MySqlDataDockerfile.dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpw

  redis:
    image: "redis"
    ports:
      - "6379:6379"


